/**
 * Represents a course or resource in the directory.
 */
export interface Course {
  /** Unique identifier */
  id: string;
  /** When added to directory (ISO string) */
  created_at: string;
  /** Last updated (ISO string) */
  updated_at: string;
  /** URL to a cover image for the resource */
  image_url?: string | null;
  /** Headline/title of the content */
  title: string;
  /** Subtitle or secondary headline */
  subtitle?: string | null;
  /** Short summary */
  description: string;
  /** Resource type */
  type: CourseType;
  /** e.g., 'Coursera', 'GitHub', 'YouTube' */
  source_platform: string;
  /** Link to the original resource */
  source_url: string;
  /** Author or organization name */
  author?: string | null;
  /** Additional metadata */
  metadata?: Record<string, unknown>;
  /** Technology stack, topics, etc. */
  tags: string[];
  /** Is this a featured resource? */
  featured: boolean;
  /** Intended audience for the content */
  audience: string[];
  /** Estimated time to complete (e.g., "8 hours") */
  duration: string;
  /** Difficulty level */
  difficulty: Difficulty;
  /** List of main topics covered */
  topics: string[];
}

export enum CourseType {
  Course = "course",
  Repository = "repository",
  Event = "event",
  Tool = "tool",
}

export enum Difficulty {
  Beginner = "Beginner",
  Intermediate = "Intermediate",
  Advanced = "Advanced",
}

// Dummy data for courses
export const dummyCourses: Course[] = [
  {
    id: "1",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    image_url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80",
    title: "Introduction to AI",
    subtitle: "Learn the basics of Artificial Intelligence",
    description: "A beginner-friendly course covering the fundamentals of AI, including history, applications, and basic algorithms.",
    type: CourseType.Course,
    source_platform: "Coursera",
    source_url: "https://coursera.org/ai-intro",
    author: "Andrew Ng",
    metadata: {},
    tags: ["AI", "Beginner"],
    featured: true,
    audience: ["Students", "Professionals"],
    duration: "8 hours",
    difficulty: Difficulty.Beginner,
    topics: ["AI Basics", "History", "Applications"],
  },
  {
    id: "2",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    image_url: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=400&q=80",
    title: "Deep Learning Specialization",
    subtitle: "Master deep learning, and break into AI",
    description: "A comprehensive specialization that helps you understand deep learning, neural networks, and how to build AI systems.",
    type: CourseType.Course,
    source_platform: "Coursera",
    source_url: "https://coursera.org/deep-learning",
    author: "Andrew Ng",
    metadata: {},
    tags: ["Deep Learning", "Neural Networks"],
    featured: true,
    audience: ["Intermediate Learners"],
    duration: "40 hours",
    difficulty: Difficulty.Intermediate,
    topics: ["Neural Networks", "Backpropagation", "CNNs", "RNNs"],
  },
  {
    id: "3",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    image_url: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80",
    title: "Advanced Machine Learning",
    subtitle: "Push your ML skills to the next level",
    description: "An advanced course for those who want to dive deeper into machine learning algorithms and real-world applications.",
    type: CourseType.Course,
    source_platform: "edX",
    source_url: "https://edx.org/advanced-ml",
    author: "Jane Doe",
    metadata: {},
    tags: ["Machine Learning", "Advanced"],
    featured: false,
    audience: ["Advanced Learners", "Researchers"],
    duration: "60 hours",
    difficulty: Difficulty.Advanced,
    topics: ["Ensemble Methods", "Reinforcement Learning", "NLP"],
  },
  {
    id: "4",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    image_url: "https://images.unsplash.com/photo-1503676382389-4809596d5290?auto=format&fit=crop&w=400&q=80",
    title: "Python for Everybody",
    subtitle: "Programming basics with Python",
    description: "A hands-on course for beginners to learn Python programming and problem-solving skills.",
    type: CourseType.Course,
    source_platform: "Coursera",
    source_url: "https://coursera.org/python-everybody",
    author: "Charles Severance",
    metadata: {},
    tags: ["Python", "Programming", "Beginner"],
    featured: false,
    audience: ["Students", "Beginners"],
    duration: "12 hours",
    difficulty: Difficulty.Beginner,
    topics: ["Python Basics", "Data Structures", "Functions"],
  },
  {
    id: "5",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    image_url: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=400&q=80",
    title: "Full Stack Web Development",
    subtitle: "Build modern web applications",
    description: "Learn to build and deploy full stack web applications using JavaScript, React, and Node.js.",
    type: CourseType.Course,
    source_platform: "Udemy",
    source_url: "https://udemy.com/full-stack-web-dev",
    author: "Angela Yu",
    metadata: {},
    tags: ["Web Development", "Full Stack", "JavaScript"],
    featured: true,
    audience: ["Developers", "Students"],
    duration: "50 hours",
    difficulty: Difficulty.Intermediate,
    topics: ["React", "Node.js", "APIs", "MongoDB"],
  },
  {
    id: "6",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    image_url: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=400&q=80",
    title: "Data Science Bootcamp",
    subtitle: "Become a data scientist",
    description: "A comprehensive bootcamp covering data analysis, visualization, and machine learning.",
    type: CourseType.Course,
    source_platform: "DataCamp",
    source_url: "https://datacamp.com/data-science-bootcamp",
    author: "Emily Chen",
    metadata: {},
    tags: ["Data Science", "Machine Learning"],
    featured: false,
    audience: ["Professionals", "Students"],
    duration: "80 hours",
    difficulty: Difficulty.Intermediate,
    topics: ["Pandas", "NumPy", "Scikit-learn", "Visualization"],
  },
  {
    id: "7",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    image_url: "https://images.unsplash.com/photo-1461344577544-4e5dc9487184?auto=format&fit=crop&w=400&q=80",
    title: "JavaScript: The Advanced Concepts",
    subtitle: "Deep dive into JavaScript",
    description: "Master advanced JavaScript concepts and patterns for professional development.",
    type: CourseType.Course,
    source_platform: "Udemy",
    source_url: "https://udemy.com/advanced-javascript",
    author: "Andrei Neagoie",
    metadata: {},
    tags: ["JavaScript", "Advanced"],
    featured: false,
    audience: ["Developers", "Advanced Learners"],
    duration: "20 hours",
    difficulty: Difficulty.Advanced,
    topics: ["Closures", "Async/Await", "Design Patterns"],
  },
  {
    id: "8",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    image_url: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=400&q=80",
    title: "Introduction to Databases",
    subtitle: "Learn SQL and database design",
    description: "A beginner's guide to relational databases, SQL queries, and normalization.",
    type: CourseType.Course,
    source_platform: "edX",
    source_url: "https://edx.org/intro-databases",
    author: "John Smith",
    metadata: {},
    tags: ["SQL", "Databases", "Beginner"],
    featured: false,
    audience: ["Students", "Professionals"],
    duration: "10 hours",
    difficulty: Difficulty.Beginner,
    topics: ["SQL", "ER Diagrams", "Normalization"],
  },
  {
    id: "9",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    image_url: "https://images.unsplash.com/photo-1465101178521-c1a9136a3b99?auto=format&fit=crop&w=400&q=80",
    title: "React - The Complete Guide",
    subtitle: "Build scalable React apps",
    description: "A complete course on React, including hooks, context, and advanced patterns.",
    type: CourseType.Course,
    source_platform: "Udemy",
    source_url: "https://udemy.com/react-complete-guide",
    author: "Maximilian Schwarzmüller",
    metadata: {},
    tags: ["React", "Frontend", "JavaScript"],
    featured: true,
    audience: ["Developers", "Students"],
    duration: "40 hours",
    difficulty: Difficulty.Intermediate,
    topics: ["React", "Hooks", "Context API", "Redux"],
  },
  {
    id: "10",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    image_url: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=400&q=80",
    title: "Natural Language Processing with Python",
    subtitle: "NLP fundamentals and applications",
    description: "Learn the basics of NLP, text processing, and building language models with Python.",
    type: CourseType.Course,
    source_platform: "Coursera",
    source_url: "https://coursera.org/nlp-python",
    author: "Susan Li",
    metadata: {},
    tags: ["NLP", "Python", "Machine Learning"],
    featured: false,
    audience: ["Students", "Researchers"],
    duration: "18 hours",
    difficulty: Difficulty.Intermediate,
    topics: ["Text Processing", "Language Models", "NLTK"],
  },
  {
    id: "11",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    image_url: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=400&q=80",
    title: "Introduction to Cloud Computing",
    subtitle: "Cloud fundamentals for everyone",
    description: "Understand the basics of cloud computing, deployment models, and cloud services.",
    type: CourseType.Course,
    source_platform: "edX",
    source_url: "https://edx.org/cloud-computing",
    author: "Michael Brown",
    metadata: {},
    tags: ["Cloud", "Beginner", "IT"],
    featured: false,
    audience: ["Students", "Professionals"],
    duration: "15 hours",
    difficulty: Difficulty.Beginner,
    topics: ["Cloud Models", "IaaS", "PaaS", "SaaS"],
  },
  {
    id: "12",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    image_url: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80",
    title: "Kubernetes for Developers",
    subtitle: "Container orchestration made easy",
    description: "Learn how to deploy, manage, and scale containerized applications using Kubernetes.",
    type: CourseType.Course,
    source_platform: "Pluralsight",
    source_url: "https://pluralsight.com/kubernetes-for-developers",
    author: "Alex Johnson",
    metadata: {},
    tags: ["Kubernetes", "DevOps", "Containers"],
    featured: false,
    audience: ["Developers", "DevOps Engineers"],
    duration: "25 hours",
    difficulty: Difficulty.Intermediate,
    topics: ["Kubernetes", "Containers", "Deployment", "Scaling"],
  },
  {
    id: "13",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    image_url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80",
    title: "Algorithms and Data Structures",
    subtitle: "Essential CS concepts",
    description: "A foundational course on algorithms, data structures, and problem-solving techniques.",
    type: CourseType.Course,
    source_platform: "Coursera",
    source_url: "https://coursera.org/algorithms-data-structures",
    author: "Robert Sedgewick",
    metadata: {},
    tags: ["Algorithms", "Data Structures", "CS"],
    featured: false,
    audience: ["Students", "Developers"],
    duration: "30 hours",
    difficulty: Difficulty.Intermediate,
    topics: ["Sorting", "Searching", "Graphs", "Trees"],
  },
  {
    id: "14",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    image_url: "https://images.unsplash.com/photo-1461344577544-4e5dc9487184?auto=format&fit=crop&w=400&q=80",
    title: "iOS App Development with Swift",
    subtitle: "Build iOS apps from scratch",
    description: "Learn to design and develop iOS applications using Swift and Xcode.",
    type: CourseType.Course,
    source_platform: "Udemy",
    source_url: "https://udemy.com/ios-app-development-swift",
    author: "Angela Yu",
    metadata: {},
    tags: ["iOS", "Swift", "Mobile Development"],
    featured: false,
    audience: ["Students", "Developers"],
    duration: "35 hours",
    difficulty: Difficulty.Intermediate,
    topics: ["Swift", "UIKit", "Xcode", "App Design"],
  },
  {
    id: "15",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    image_url: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=400&q=80",
    title: "Cybersecurity Fundamentals",
    subtitle: "Protect systems and data",
    description: "An introduction to cybersecurity principles, threats, and defense mechanisms.",
    type: CourseType.Course,
    source_platform: "edX",
    source_url: "https://edx.org/cybersecurity-fundamentals",
    author: "Lisa White",
    metadata: {},
    tags: ["Cybersecurity", "Security", "Beginner"],
    featured: false,
    audience: ["Students", "IT Professionals"],
    duration: "20 hours",
    difficulty: Difficulty.Beginner,
    topics: ["Threats", "Encryption", "Network Security"],
  },
  {
    id: "16",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    image_url: "https://images.unsplash.com/photo-1465101178521-c1a9136a3b99?auto=format&fit=crop&w=400&q=80",
    title: "Blockchain Basics",
    subtitle: "Understand blockchain technology",
    description: "A beginner's guide to blockchain, cryptocurrencies, and decentralized applications.",
    type: CourseType.Course,
    source_platform: "Coursera",
    source_url: "https://coursera.org/blockchain-basics",
    author: "Satoshi Nakamoto",
    metadata: {},
    tags: ["Blockchain", "Cryptocurrency", "Beginner"],
    featured: false,
    audience: ["Students", "Professionals"],
    duration: "10 hours",
    difficulty: Difficulty.Beginner,
    topics: ["Blockchain", "Bitcoin", "Smart Contracts"],
  },
  {
    id: "17",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    image_url: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=400&q=80",
    title: "Frontend Masters: CSS Grid & Flexbox",
    subtitle: "Modern CSS layout techniques",
    description: "Master CSS Grid and Flexbox to create responsive, modern web layouts.",
    type: CourseType.Course,
    source_platform: "Frontend Masters",
    source_url: "https://frontendmasters.com/css-grid-flexbox",
    author: "Rachel Andrew",
    metadata: {},
    tags: ["CSS", "Frontend", "Web Design"],
    featured: false,
    audience: ["Designers", "Developers"],
    duration: "8 hours",
    difficulty: Difficulty.Intermediate,
    topics: ["CSS Grid", "Flexbox", "Responsive Design"],
  },
  {
    id: "18",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    image_url: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=400&q=80",
    title: "Google Cloud Platform Essentials",
    subtitle: "Get started with GCP",
    description: "A practical introduction to Google Cloud Platform services and tools.",
    type: CourseType.Course,
    source_platform: "Coursera",
    source_url: "https://coursera.org/gcp-essentials",
    author: "Priya Patel",
    metadata: {},
    tags: ["Cloud", "GCP", "Beginner"],
    featured: false,
    audience: ["Students", "IT Professionals"],
    duration: "12 hours",
    difficulty: Difficulty.Beginner,
    topics: ["GCP", "Compute Engine", "Storage", "Networking"],
  },
  {
    id: "19",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    image_url: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=400&q=80",
    title: "Linux Command Line Basics",
    subtitle: "Master the Linux terminal",
    description: "Learn essential Linux commands and shell scripting for productivity and automation.",
    type: CourseType.Course,
    source_platform: "Udemy",
    source_url: "https://udemy.com/linux-command-line",
    author: "Jason Cannon",
    metadata: {},
    tags: ["Linux", "Command Line", "Beginner"],
    featured: false,
    audience: ["Students", "IT Professionals"],
    duration: "10 hours",
    difficulty: Difficulty.Beginner,
    topics: ["Bash", "Shell Scripting", "File System"],
  },
  {
    id: "20",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    image_url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80",
    title: "TensorFlow Developer Certificate in 2024: Zero to Mastery",
    subtitle: "Become a certified TensorFlow developer",
    description: "Prepare for the TensorFlow Developer Certificate exam with hands-on projects and deep learning fundamentals.",
    type: CourseType.Course,
    source_platform: "Udemy",
    source_url: "https://udemy.com/tensorflow-developer-certificate",
    author: "Daniel Bourke",
    metadata: {},
    tags: ["TensorFlow", "Deep Learning", "Certification"],
    featured: true,
    audience: ["Developers", "Students"],
    duration: "30 hours",
    difficulty: Difficulty.Intermediate,
    topics: ["TensorFlow", "Neural Networks", "Projects"],
  },
]; 